# Trabalho Final Machine Learning - Classificação de Doenças Cardíacas por KNN, Random Forest e SVM (Support Vector Machines)

## Aluno: Carlos Henrique Pinheiro Cordeiro
#### Link para download do dataset utilizado: https://archive.ics.uci.edu/dataset/45/heart+disease

---

### Primeiramente deve se estabelecer uma base para as três técnicas. Consistindo em resgatar os dados desejados, para que seja realizado um pré-processamento
### Iniciando pelo resgate dos dados para um dataframe do Pandas

In [1]:
import pandas as pd
import numpy as np
aColunas = ["age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "target"]
oDfDados = pd.read_csv("dataset/processed.cleveland.data", names=aColunas, na_values='?')

### Agora, se tem o pré-processamento dos dados, limpando valores nulos e realizando separações dos conjuntos de teste e treinamento

In [2]:
from sklearn.model_selection import train_test_split
oDfDados = oDfDados.dropna()

aX = oDfDados.drop("target", axis=1)
aY = oDfDados["target"]

xTreinamento, xTeste, yTreinamento, yTeste = train_test_split(aX, aY, test_size=0.2, random_state=42)

### A partir daqui, com a base estabelecida (dados obtidos e limpos) pode-se dar início a etapa de testes com os três modelos selecionados: KNN, Random Forest e SVM

---------------------------------------------------------

# KNN

### Normalização dos dados e treinamento do modelo KNN

In [3]:
from sklearn.preprocessing import StandardScaler

oScaler         = StandardScaler()
xTreinamentoKnn = oScaler.fit_transform(xTreinamento)
xTesteKnn       = oScaler.transform(xTeste)

### Criação do modelo KNN para o melhor K definido de forma iterativa

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
 
aValoresK = np.array([]);
for k in range(1, 101):
    aValoresK = np.append(aValoresK, [KNeighborsClassifier(n_neighbors=k).fit(xTreinamentoKnn, yTreinamento).score(xTesteKnn, yTeste)])

print("O melhor K definido é: "+str(aValoresK.max())+", tendo como K = "+str(aValoresK.argmax()+1))

oModeloKnn = KNeighborsClassifier(n_neighbors=aValoresK.argmax()+1);
oModeloKnn.fit(xTreinamentoKnn, yTreinamento)
print(oModeloKnn.score(xTesteKnn, yTeste))


O melhor K definido é: 0.7, tendo como K = 2
0.7


### Realização de previsões com o modelo a partir do conjunto de teste

In [10]:
yPrevisto = oModeloKnn.predict(xTesteKnn)

iAcuracia = accuracy_score(yTeste, yPrevisto)
print(f"Acurácia: {iAcuracia:.2f}")

print("\nMatriz de Confusão:")
print(confusion_matrix(yTeste, yPrevisto))

print("\nRelatório de Classificação:")
print(classification_report(yTeste, yPrevisto))


Acurácia: 0.70

Matriz de Confusão:
[[35  1  0  0  0]
 [ 2  6  1  0  0]
 [ 3  2  0  0  0]
 [ 3  2  1  1  0]
 [ 1  2  0  0  0]]

Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.80      0.97      0.88        36
           1       0.46      0.67      0.55         9
           2       0.00      0.00      0.00         5
           3       1.00      0.14      0.25         7
           4       0.00      0.00      0.00         3

    accuracy                           0.70        60
   macro avg       0.45      0.36      0.33        60
weighted avg       0.66      0.70      0.64        60



c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
